name: fabspin
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.5.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  geolocator: ^13.0.1
  google_fonts: ^4.0.4
  http: ^0.13.0
  shared_preferences: ^2.0.8
  flutter_launcher_icons: ^0.13.1
  scroll_to_animate_tab: ^0.0.3
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0
  permission_handler:
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  google_maps_flutter: ^2.9.0
  intl:
  geocoding:
  google_maps_webservice:
  # flutter_google_places: ^0.3.0
  mime: ^1.0.6
  firebase_messaging: ^15.1.2
  firebase_core:
  flutter_local_notifications:
  firebase_analytics: ^11.3.2
  razorpay_flutter: ^1.3.7
  connectivity_plus: ^6.0.5
  flutter_polyline_points: ^1.0.0
  location: ^6.0.0
  ionicons: ^0.2.2
  change_app_package_name: ^1.4.0
  flutter_native_splash: ^2.4.2
  # google_api_headers: ^1.6.0
  google_places_flutter: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Fabspin.png"
 
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/icon/splash.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill




flutter:

  uses-material-design: true

  assets:
    - assets/images/otp.png
    - assets/images/otp1.png
    - assets/images/garment-cleaning.jpg
    - assets/images/shoe-cleaning.jpg
    - assets/images/carpet-cleaning.jpg
    - assets/images/sofa-cleaning.jpg
    - assets/icon/confirmOrder.gif
    - assets/images/bg.jpg
    - assets/icon/splash.png
    - assets/icon/fabspinsplash.png
    - assets/images/Fabspin.png
    - assets/images/Fabspin.jpeg
    - assets/images/banner2.gif
    - assets/images/banner1.gif
    - assets/images/banner3.jpeg
    - assets/images/bannersmall.gif
    - assets/images/promotion1.jpeg
    - assets/images/promotion2.jpeg
    - assets/icon/shoe-cleaning-icon.png
    - assets/icon/dry-clean-icon.png
    - assets/icon/steam-iron-icon.png
  #   - images/a_dot_ham.jpeg

